### PR TITLE
Migrate build to CMake

### PR DESCRIPTION
**Pull request by ForNeVeR**
This is a part of #1.

CMake is a cross-platform build engine, able to generate Visual Studio solutions, makefiles etc, and it's de-facto standard for today's cross-platform C++ development.

### CODE REVIEW

**Comment by impworks** [comment]
I'm not sure about completely removing the VS project. To work in VS, now you need `cmake` to first *generate* the project for you?

**Comment by ForNeVeR** [comment]
Generally that's true, but not for VS2017.

With VS2017, you could open a folder with `CMakeLists.txt` (via File → Open → Folder…), and it will then load CMake project information.

I've just verified: it loads the project and gives access to common build / debug functions. The only inconvenience I've found is that CMake menu items have different hotkeys (my F5 / F6 doesn't work for CMake). Debug and build works.

So, when working with VS2017, the user actually have two options: either load the CMake project or generate `.sln` file and work with it.

**Comment by impworks** [comment]
Okay then, looks good to me!

**Comment by ForNeVeR** [comment]
Thanks for the review!

**Pull request merged**
