### PR TITLE
Enable automated testing

### LINKED ISSUE #2: Unit tests
Set up unit test system, execute tests at the CI servers.

### PR DESCRIPTION
**Pull request by ForNeVeR**
This PR enables automated testing both on Windows and Linux.

We're still only trying to compile the scripts; I'll create another issue about testing the running of the programs.

Closes #2.

### CODE REVIEW

**Comment by impworks** [comment]
The builds seem to fail because compilation requires `malco.ini` to be present in the folder with the executable. If I remember correctly, the contents of the file is not actually used, but its presence is still checked. You can comment out the check or just drop in an empty file.

**Comment by ForNeVeR** [comment]
Ah, really, your hypothesis is right.

The tests **should** actually fail, because malco currently experiences runtime compilation error due to #10. Although, Appveyor configuration doesn't work right; I'll fix the test environment for now.

Regarging `malco.ini` — my current plan is to first make the minimal changes for the things to run smoothly, and _then_ start big refactoring and making any additional changes.

**Comment by impworks** [comment]
I suppose adding an empty file is the smallest change possible. Otherwise you can't check if #10 is fixed or not, because Malco will always fail before even trying to parse the file.

**Review by impworks — APPROVED** [review]

**Comment by ForNeVeR** [comment]
@impworks I've fixed the issue. Look, we already have the **empty `malco.ini` file**™ in our repository. I just had to set up the root as a working directory for tests (I have already done that for Linux build, but forget to do the same for Windows). Everything is okay now.

Thanks for the review!

**Comment by impworks** [comment]
You are right. Now the build fails due to the regular expression error, as expected.

**Pull request merged**
